-- Enable Row Level Security (RLS) is recommended, but for initial migration we might start open or with basic policies.
-- For this setup, we will create tables.

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS users (
  nip TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL, -- 'admin', 'pengawas', 'kepala-sekolah', 'guru'
  school TEXT,
  email TEXT,
  phone TEXT,
  "password" TEXT, -- If we store passwords manually (not recommended if using Supabase Auth, but needed for legacy sync)
  "managedSchools" TEXT[], -- Array of strings
  "workloadEvidence_v2" JSONB, -- Stores the record of evidence IDs
  "workloadScores_v2" JSONB, -- Stores the scores
  "lastSeen" TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. SUPERVISIONS TABLE
CREATE TABLE IF NOT EXISTS supervisions (
  id TEXT PRIMARY KEY,
  "teacherNip" TEXT NOT NULL,
  "teacherName" TEXT,
  school TEXT NOT NULL,
  date DATE,
  semester TEXT,
  year TEXT,
  scores JSONB, -- Record<string, number>
  notes JSONB, -- Record<string, string>
  conclusion TEXT,
  "followUp" TEXT,
  "finalScore" NUMERIC,
  type TEXT, -- 'administration', 'observation', 'planning', 'planning_deep'
  subject TEXT,
  topic TEXT,
  "learningGoals" TEXT,
  grade TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SCHOOL VISITS TABLE (Laporan Kunjungan Pengawas)
CREATE TABLE IF NOT EXISTS school_visits (
  id TEXT PRIMARY KEY,
  "schoolName" TEXT NOT NULL,
  "visitorNip" TEXT NOT NULL,
  "visitorName" TEXT,
  date DATE,
  purpose TEXT,
  findings TEXT,
  recommendations TEXT,
  status TEXT DEFAULT 'planned', -- 'planned', 'completed'
  "createdAt" TIMESTAMPTZ DEFAULT NOW()
);

-- 4. SCHOOL STATS TABLE (Aggregation)
-- This might need to be updated via triggers or scheduled functions, 
-- but for now we'll create the table to store the aggregated state.
CREATE TABLE IF NOT EXISTS school_stats (
  "schoolName" TEXT PRIMARY KEY,
  teachers JSONB, -- Stores teacher stats object
  "totalDocs" INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. SETTINGS TABLE (Running Text, etc.)
CREATE TABLE IF NOT EXISTS settings (
  id TEXT PRIMARY KEY,
  text TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. GENERATED DOCS LOG
CREATE TABLE IF NOT EXISTS generated_docs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school TEXT NOT NULL,
  "docType" TEXT NOT NULL,
  "fileUrl" TEXT NOT NULL,
  "generatedBy" TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ENABLE REALTIME
-- You need to enable Realtime for these tables in the Supabase Dashboard > Database > Replication
-- OR run:
-- alter publication supabase_realtime add table users, supervisions, school_visits, school_stats, settings, generated_docs;

-- POLICIES (Simple Public Access for now - WARNING: NOT SECURE FOR PRODUCTION)
-- You should refine these based on RLS later.

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON users FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON users FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON users FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON users FOR DELETE USING (true);

ALTER TABLE supervisions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON supervisions FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON supervisions FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON supervisions FOR UPDATE USING (true);

ALTER TABLE school_visits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON school_visits FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON school_visits FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON school_visits FOR UPDATE USING (true);

ALTER TABLE school_stats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON school_stats FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON school_stats FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON school_stats FOR UPDATE USING (true);

ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON settings FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON settings FOR UPDATE USING (true);

ALTER TABLE generated_docs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON generated_docs FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON generated_docs FOR INSERT WITH CHECK (true);
